ia mZ \mathbb{Z}
ia mN \mathbb{N}
ia mC \mathbb{C}
ia mR \mathbb{R}
ia mQ \mathbb{Q}
ia SET \{\}<Left><Left>
ia MATRIX \begin{bmatrix}<CR>\end{bmatrix}
ia HWSEC \section{}<CR>\vspace{2cm}
ia enum \begin{enumerate}<CR>\item<CR>\end{enumerate}
inoremap \[<CR> \[<CR>\]<C-d><C-o>O
